# Image Import and Blur
Blur Sigma: 0.5

#Small Object and Hole Removal
Min Hole Size: 300 #pixels
Min Object Size: 400 #pixels

# Skeletonisation
Min Spur Line Length: 50 #pixels
Min Length for Internal Line: 30 # If length < this number edge's nodes will be merged into one
Minimum Vessel Width: 0 #pixels

#Save Results
Save Image: True
Show Image: False

#Path and Savename
Img Path: "C:\\Users\\harry\\Downloads\\Tester\\"
Results Path: ./Results/
Spreadsheet Output Path: .\\17_05_24_create_STATS.csv



